<?php

/**
 * @file
 * Preprocess module functions and hooks.
 */

/**
 * Implements hook_preprocess_node().
 */
function preprocess_preprocess_node(&$variables) {
  $entity_type = $variables['theme_hook_original'];
  $plugin_service_id = ($entity_type === 'node') ? 'plugin.manager.preprocess_node_plugin_manager' : 'plugin.manager.preprocess_paragraph_plugin_manager';

  $bundle = $variables[$entity_type]->getType();
  $view_mode = $variables['elements']['#view_mode'];

  $plugin_service = \Drupal::service($plugin_service_id);
  $theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();

  // Do discovery only once per request.
  $plugins = &drupal_static("preprocess_plugins_$bundle");
  if (NULL === $plugins) {
    $plugins = $plugin_service->getDefinitions();
  }

  // Select which preprocess plugin should be called.
  foreach ($plugins as $plugin_id => $plugin) {
    if ($plugin['bundle'] === $bundle && $plugin['view_mode'] === $view_mode && $plugin['theme'] === $theme) {
      // Instantiate only plugins that are needed.
      if (!isset($plugin['instance'])) {
        // Save instances for later use.
        $plugins[$plugin_id]['instance'] = $plugin_service->createInstance($plugin_id);
      }
      $plugins[$plugin_id]['instance']->process($variables);
      break;
    }
  }
}
